const groupsNames = [
				{ name: "Adventure",
					class: "adventure",
					price: 4,
					channels: ["Peachtree TV", "Space", "Bravo", "American Heroes Channel", "Paramount"],
					channelsPrice: ["$5.00", "$8.00", "$8.00", "$1.99", "$2.99"],
					channelsNumber: [121, 122, 123, 124, 125],
					ids: ["peachtree", "space", "bravo", "american-heroes-channel", "paramount"]
				},
				{ name: "Cinema",
					class: "cinema",
					price: 3,
					channels: ["CHCH", "IFC", "Documentary", "Rewind Channel", "Silver Screen Classics"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [261, 262, 264, 265, 266],
					ids: ["chch", "ifc", "documentary", "rewindchannel", "silver-screen-classics"]
				},
				{ name: "Divertissement",
					class: "divertissement",
					price: 3,
					channels: ["LCN", "ICI ARTV", "Canal D", "Z", "Zeste", "Évasion", "ICI Explora"],
					channelsPrice: ["$1.99", "$2.99", "$8.00", "$8.00", "$4.00", "$4.00", "$4.00"],
					channelsNumber: [138, 421, 423, 424, 425, 426, 427],
					ids: ["lcn", "ici-artv", "canal-d", "z", "zeste", "evasion", "ici-explora"]
				},
				{ name: "Entertainment",
					class: "entertainment",
					price: 4,
					channels: ["Showcase", "E!", "OWN", "The Comedy Network", "Gusto"],
					channelsPrice: ["$1.99", "$6.00", "$4.00", "$8.00", "$6.00"],
					channelsNumber: [111, 113, 114, "115-116", 117],
					ids: ["showcase", "e!", "own", "the-comedy-network", "gusto"]
				},
				{ name: "Explore",
					class: "explore",
					price: 4,
					channels: ["National Geographic Channel", "Discovery Science", "DIY Network", "Nat Geo Wild", "Investigation Discovery"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [272, 273, 275, 276, 277],
					ids: ["national-geographic-channel", "discovery-science", "diy-network", "nat-geo-wild", "investigation-discovery"]
				},
				{ name: "Famille",
					class: "famille",
					price: 4,
					channels: ["VRAK", "Télé-Québec", "Télétoon", "RDS Info", "addikTV", "Series+"],
					channelsPrice: ["$8.00", "$1.99", "$1.99", "$1.99", "$2.99", "$1.99"],
					channelsNumber: [411, 412, 413, 414, 415, 422],
					ids: ["vrak", "Tele-quebec", "teletoon", "rds-info", "addiktv", "series+"]
				},
				{ name: "Family",
					class: "family",
					price: 5,
					channels: ["Disney Channel", "TELETOON", "Family Channel", "Treehouse", "Disney Junior", "Cartoon Network", "Family Jr.", "CHRGD", "Disney XD"],
					channelsPrice: ["$2.99", "$4.00", "$2.99", "$4.00", "$2.99", "$4.00", "$2.99", "$2.99", "$2.99"],
					channelsNumber: [150, "151-152", "153-154", 155, 156, 157, 158, 159, 160],
					ids: ["Disney Channel", "TELETOON", "Family Channel", "Treehouse", "Disney Junior", "Cartoon Network", "Family Jr.", "CHRGD", "Disney XD"]
				},
				{ name: "HD Discoery",
					class: "hd-discoery",
					price: 4,
					channels: ["Wild TV HD", "Discovery Velocity HD"],
					channelsPrice: ["$1.99", "$8.00"],
					channelsNumber: [1185, 1621],
					ids: ["wild-tv-hd", "discovery-velocity-hd"]
				},
				{ name: "HD HiFi",
					class: "hd-hifi",
					price: 5,
					channels: ["Smithsonian Channel", "Love Nature", "HIFI", "BBC Earth"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [1601, 1602, 1603, 1604],
					ids: ["smithsonian-channel", "love-nature", "hifi", "bbc-earth"]
				},
				{ name: "HD Hollywood Suite",
					class: "hd-hollywood-suite",
					price: 5,
					channels: ["Hollywood Suite 70s Movies", "Hollywood Suite 80s Movies", "Hollywood Suite 90s Movies", "Hollywood Suite 00s Movies"],
					channelsPrice: ["$2.50", "$2.50", "$2.50", "$2.50"],
					channelsNumber: [1611, 1612, 1613,1614],
					ids: ["hollywood-suite-70s-movies", "hollywood-suite-80s-movies", "hollywood-suite-90s-movies", "hollywood-suite-00s-movies"]
				},
				{ name: "Information",
					class: "information",
					price: 3,
					channels: ["CP24", "TVO"],
					channelsPrice: ["$8.00", "$1.99"],
					channelsNumber: [283, 284],
					ids: ["cp24", "tvo"]
				},
				{ name: "Jeunesse",
					class: "jeunesse",
					price: 3,
					channels: ["Télémagino", "BabyTV (French)", "La Chaîne Disney"],
					channelsPrice: ["$2.99", "$1.99", "$1.99"],
					channelsNumber: [441, 442, 443],
					ids: ["telemagino", "babytv-french", "la-chaine-disney"]
				},
				{ name: "Kids Plus",
					class: "kids-plus",
					price: 3,
					channels: ["Animal Planet", "BBC Kids", "Nickelodeon", "BabyTV"],
					channelsPrice: ["$4.00"],
					channelsNumber: [138],
					ids: ["animal-planet", "bbc-kids", "nickelodeon", "babytv"]
				},
				{ name: "Life",
					class: "life",
					price: 5,
					channels: ["Slice", "W Network", "HGTV", "Food Network", "CosmoTV"],
					channelsPrice: ["$1.99", "$4.00", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [131, "132-133", 134, 135, 136],
					ids: ["slice", "w-network", "hgtv", "food-network", "cosmotv"]
				},
				{ name: "Lifestyle",
					class: "lifestyle",
					price: 3,
					channels: ["FYI", "Fashion Television Channel", "ONE", "OUTtv"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [292, 293, 294, 295],
					ids: ["FYI", "fashion-television-channel", "one", "outtv"]
				},
				{ name: "Medley",
					class: "medley",
					price: 3,
					channels: ["BET", "A.Side TV", "Makeful", "MTV2", "MTV"],
					channelsPrice: ["$2.99", "$1.99", "$1.99", "$1.99", "$6.00"],
					channelsNumber: [314, 321, 322, 324, 326],
					ids: ["bet", "a-side-tv", "makeful", "mtv2", "mtv"]
				},
				{ name: "Movie Flicks",
					class: "movie-flicks",
					price: 4,
					channels: ["WGN Chicago", "Action", "Lifetime", "AMC", "Turner Classic Movies"],
					channelsPrice: [" ", "$1.99", "$1.99", "$7.00", "$6.00"],
					channelsNumber: [222, 241, 244, 247, 248],
					ids: ["wgn-chicago", "action", "lifetime", "amc", "turner-classic-movies"]
				},
				{ name: "Movie Picks",
					class: "movie-picks",
					price: 4,
					channels: ["MovieTime", "DejaView", "ABC Spark", "Cooking Channel", "FX"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [231, 233, 234, 236, 237],
					ids: ["movietime", "dejaview", "abc-spark", "cooking-channel", "fx"]
				},
				{ name: "Music",
					class: "music",
					price: 3,
					channels: ["Stingray Vibe", "Stingray Loud", "Stingray Retro", "Stingray Juicebox"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [311, 313, 315, 323],
					ids: ["stingray-vibe", "stingray-loud", "stingray-retro", "stingray-juicebox"]
				},
				{ name: "News",
					class: "news",
					price: 4,
					channels: ["CTV News Channel", "BNN Bloomberg", "CNBC", "Fox News", "MSNBC"],
					channelsPrice: ["$2.80", "$6.00", "$4.00", "$1.99", "$4.00"],
					channelsNumber: [141, 142, 144, 145, 149],
					ids: ["ctv-news-channel", "bnn-bloomberg", "cnbc", "fox-news", "msnbc"]
				},
				{ name: "Places",
					class: "places",
					price: 3,
					channels: ["BBC World News", "Travel + Escape", "Cottage Life", "BBC Canada", "BookTelevision"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [301, 302, 303, 304, 305],
					ids: ["bbc-world-news", "travel+escape", "cottage-life", "bbc-canada", "booktelevision"]
				},
				{ name: "PrimeTime 1",
					class: "primetime-1",
					price: 6,
					channels: ["A&E", "TLC", "CNN", "Discovery", "Headline News"],
					channelsPrice: ["$2.99", "$4.00", "$7.00", "$8.00", "$3.00"],
					channelsNumber: [101, 102, 103, 104, 108],
					ids: ["a&e", "tlc", "cnn", "discovery", "headline-news"]
				},
				{ name: "PrimeTime 2",
					class: "primetime-2",
					price: 4,
					channels: ["History", "DTOUR", "GSN", "CMT","NASA TV"],
					channelsPrice: ["$1.99", "$1.99", "$2.99", "$4.00", "$1.99"],
					channelsNumber: [105, 106, 107, 109, 110],
					ids: ["history", "dtour", "gsn", "cmt","nasa-tv"]
				},
				{ name: "Replay",
					class: "replay",
					price: 3,
					channels: ["Comedy Gold", "H2", "Crime + Investigation", "TLN"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$4.00"],
					channelsNumber: [162, 163, 164, 165],
					ids: ["comedy-gold", "h2", "crime+investigation", "tln"]
				},
				{ name: "Sport Champions",
					class: "sport-champions",
					price: 3,
					channels: ["RDS", "NBA TV Canada", "EuroWorld Sport", "TVA Sports"],
					channelsPrice: ["$6.00", "$1.99", "$4.00", "$1.99"],
					channelsNumber: [191, 192, 195, 197],
					ids: ["rds", "nba-tv-canada", "euroworld-sport", "tva-sports"]
				},
				{ name: "Sports Enthusiasts",
					class: "sports-enthusiasts",
					price: 3,
					channels: ["World Fishing Network", "Wild TV", "ESPN Classic"],
					channelsPrice: ["$1.99", "$1.99", "$1.99"],
					channelsNumber: [183, 185, 202],
					ids: ["world-fishing-network", "wild-tv", "espn-classic"]
				},
				{ name: "Sports Fans",
					class: "sports-fans",
					price: 15,
					channels: ["Fight Network", "Sportsnet - Sportsnet 4K also available",
										 "FOX Sports Racing", "OLN", "NFL Network", 
										 "Sportsnet 590 The FAN", "Sportsnet 360", "Golf Channel", 
										 "Sportsnet ONE - Sportsnet One 4K also available", 
										 "MLB Network"],
					channelsPrice: ["$1.99", "$25.00", "$2.99", "$6.00", "$4.00", 
													"$1.99", "$10.00", "$4.00", "$14.00", "$2.99"],
					channelsNumber: [170, "171-174", 175, 176, 177, 178, 181, 182, 187, 188],
					ids: ["fight-network", "sportsnet", "fox-sports-racing", "oln", 
								"nfl-network", "sportsnet-590-the-fan", "sportsnet-360", 
								"golf-channel", "sportsnet-one", "mlb-network"]
				},
				{ name: "Super",
					class: "super",
					price: 4,
					channels: ["myTV38 Boston", "WGN Chicago", "PIX New York", "KTLA Los Angeles"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99"],
					channelsNumber: [221, 222, 223, 224],
					ids: ["mytv38-boston", "wgn-chicago", "pix-new-york", "ktla-los-angeles"]
				},
				{ name: "Time Shift East",
					class: "time-shift-east",
					price: 3,
					channels: ["CBC Toronto", "City Toronto", "Global Toronto", "CTV Montreal",
										 "NTV St. John's", "Global Maritimes", "PBS Detroit", "CTV Halifax", 
										 "CTV Kitchener", "CTV Moncton", "CTV North Bay", "CTV Ottawa", 
										 "CTV Sault Ste. Marie", "CTV Sudbury", "CTV Timmins", "CTV Toronto", 
										 "CTV Sydney"],
					channelsPrice: ["$2.99", "$2.99", "$2.99", "$2.99", "$2.99", "$2.99", "$2.99",
													"$2.99", "$2.99", "$2.99", "$2.99", "$2.99", "$2.99", "$2.99",
													"$2.99", "$2.99", "$2.99",],
					channelsNumber: [341, 342, 343, 344, 345, 346, 348, 1349, 1350, 
													 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358],
					ids: ["cbc-toronto", "city-toronto", "global-toronto", "ctv-montreal", 
								"ntv-st-Johns", "global-maritimes", "pbs-detroit", "ctv-halifax", 
								"ctv-kitchener", "ctv-moncton", "ctv-north-bay", "ctv-ottawa", 
								"ctv-sault-ste-marie", "ctv-sudbury", "ctv-timmins", "ctv-toronto",
								"ctv-sydney"]
				},
				{ name: "Time Shift West",
					class: "time-shift-west",
					price: 3,
					channels: ["City Saskatchewan", "CBC Vancouver", "CTV BC", "Global BC", 
										 "City Edmonton", "City Vancouver", "ABC Seattle", "CBS Seattle", 
										 "FOX Seattle", "NBC Seattle", "PBS Seattle", "CTV Calgary", 
										 "CTV Regina"],
					channelsPrice: ["1.99$", "$2.99", "$2.99", "$2.99", "$2.99", "$2.99",
												  "$2.99", "$2.99", "$2.99", "$2.99", "$2.99", "$2.99",
												  "$2.99"],
					channelsNumber: [330, 331, 332, 333, 334, 335, 336, 
													 337, 338, 339, 340, 1359, 1360],
					ids: ["city-saskatchewan", "cbc-vancouver", "ctv-bc", "global-bc", 
							  "city-edmonton", "city-vancouver", "abc-seattle", "cbs-seattle", 
							  "fox-seattle", "nbc-seattle", "pbs-seattle", "ctv-calgary", 
							  "ctv-regina"]
				},
				{ name: "Variété",
					class: "variete",
					price: 3,
					channels: ["Historia", "Prise 2", "CASA", "euronews (French)", 
										 "Investigation", "MusiquePlus", "Max"],
					channelsPrice: ["$1.99", "$1.99", "$1.99", "$1.99", "$4.00", 
													"$4.00", "$4.00"],
					channelsNumber: [431, 432, 433, 434, 435,436,437],
					ids: ["historia", "prise-2", "casa", "euronews-French", "investigation", 
								"musique-plus", "max"]
				},
];

export default groupsNames;